### ISSUE TITLE
How to disable the script from running during startup

### ISSUE THREAD

**Issue by deniscerri** [magliocchetti/Samsung-Quick-Share-4-All#3]

**Comment by obrobrio2000** [comment]
Go to `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp` and delete `SamsungQuickShare4All.bat`. I'll add it to the readme.

**Comment by obrobrio2000** [comment]
Go to `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp` and delete `SamsungQuickShare4All.bat`. I'll add it to the readme.
